--------------------------------------------------------
-- 1. CREACIÓN DE TABLAS FUERTES (Sin dependencias)
--------------------------------------------------------

CREATE TABLE PAIS (
    id_pais NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 9) NOT NULL,
    nom_pais VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY(id_pais)
);

CREATE TABLE CLIENTE (
    rut NUMBER(8) NOT NULL,
    dv CHAR(1) NOT NULL,
    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20),
    apaterno VARCHAR2(20) NOT NULL,
    amaterno VARCHAR2(20) NOT NULL,
    telefono VARCHAR2(12),
    email VARCHAR2(40),
    tipo_cli CHAR(1) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(rut),
    CONSTRAINT UN_CLIENTE UNIQUE(email),
    CONSTRAINT CK_CLIENTE_DV CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'))
);

CREATE TABLE MARCA (
    id_marca NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY(id_marca)
);

CREATE TABLE SERVICIO (
    id_servicio NUMBER(3) NOT NULL,
    descripcion VARCHAR2(100) NOT NULL,
    costo NUMBER(7) NOT NULL,
    CONSTRAINT PK_SERVICIO PRIMARY KEY(id_servicio)
);

CREATE TABLE TIPO_AUTOMOVIL (
    id_tipo CHAR(3) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_TIPO_AUTOMOVIL PRIMARY KEY(id_tipo)
);

CREATE TABLE MECANICO (
    cod_mecanico NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 460) NOT NULL,
    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20) NOT NULL,
    apaterno VARCHAR2(20) NOT NULL,
    amaterno VARCHAR2(20) NOT NULL,
    bono_jefatura NUMBER(10),                          -- NULL indica que no tiene jefatura asignada
    sueldo NUMBER(10) NOT NULL,
    monto_impuestos NUMBER(10) NOT NULL,
    cod_supervisor NUMBER(5),
    CONSTRAINT PK_MECANICO PRIMARY KEY(cod_mecanico),
    CONSTRAINT FK_MECANICO_MECANICO FOREIGN KEY(cod_supervisor) REFERENCES MECANICO(cod_mecanico),
    CONSTRAINT CK_MECANICO_BONO_JEFATURA CHECK(bono_jefatura >= 0),
    CONSTRAINT CK_MECANICO_SUELDO CHECK(sueldo >= 510000),
    CONSTRAINT CK_MECANICO_MONTO_IMPUESTOS CHECK(monto_impuestos >= 0)
);

--------------------------------------------------------
-- 2. CREACIÓN DE TABLAS DEPENDIENTES
--------------------------------------------------------

CREATE TABLE CIUDAD (
    id_ciudad NUMBER(3) NOT NULL,
    nom_ciudad VARCHAR2(30) NOT NULL,
    cod_pais NUMBER(3) NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY(id_ciudad),
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY(cod_pais) REFERENCES PAIS(id_pais),
    CONSTRAINT UN_CIUDAD UNIQUE(nom_ciudad, cod_pais)
);

CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3) NOT NULL,
    nom_sucursal VARCHAR2(20) NOT NULL,
    calle VARCHAR2(20) NOT NULL,
    num_calle NUMBER(4) NOT NULL,
    cod_ciudad NUMBER(3) NOT NULL,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY(id_sucursal),
    CONSTRAINT FK_SUCURSAL_CIUDAD FOREIGN KEY(cod_ciudad) REFERENCES CIUDAD(id_ciudad),
    CONSTRAINT UN_SUCURSAL UNIQUE(nom_sucursal, cod_ciudad)
);

CREATE TABLE MODELO (
    id_modelo NUMBER(5) NOT NULL,
    marca_id NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MODELO PRIMARY KEY(id_modelo, marca_id),
    CONSTRAINT FK_MODELO_MARCA FOREIGN KEY(marca_id) REFERENCES MARCA(id_marca)
);

CREATE TABLE ESTANDAR (
    cl_rut NUMBER(8) NOT NULL,
    puntaje_fidelidad NUMBER(10) NOT NULL,
    CONSTRAINT PK_ESTANDAR PRIMARY KEY(cl_rut),
    CONSTRAINT FK_ESTANDAR_CLIENTE FOREIGN KEY(cl_rut) REFERENCES CLIENTE(rut)
);

CREATE TABLE PREMIUM (
    cl_rut NUMBER(8) NOT NULL,
    pesos_clientes NUMBER(10) NOT NULL,
    monto_credito NUMBER(10) NOT NULL,
    CONSTRAINT PK_PREMIUM PRIMARY KEY(cl_rut),
    CONSTRAINT FK_PREMIUM_CLIENTE FOREIGN KEY(cl_rut) REFERENCES CLIENTE(rut)
);

CREATE TABLE AUTOMOVIL (
    patente CHAR(8) NOT NULL,
    annio NUMBER(4) NOT NULL,
    cant_puertas NUMBER(1) NOT NULL,
    km NUMBER(6) NOT NULL,
    color VARCHAR2(30) NOT NULL,
    cod_tipo_auto CHAR(3) NOT NULL,
    cod_modelo NUMBER(5) NOT NULL,
    cod_marca NUMBER(2) NOT NULL,
    cl_rut NUMBER(8) NOT NULL,
    CONSTRAINT PK_AUTOMOVIL PRIMARY KEY(patente),
    CONSTRAINT FK_AUTOMOVIL_CLIENTE FOREIGN KEY(cl_rut) REFERENCES CLIENTE(rut),
    CONSTRAINT FK_AUTOMOVIL_MODELO FOREIGN KEY(cod_modelo, cod_marca) REFERENCES MODELO(id_modelo, marca_id),
    CONSTRAINT FK_AUTOMOVIL_TIPO_AUTOMOVIL FOREIGN KEY(cod_tipo_auto) REFERENCES TIPO_AUTOMOVIL(id_tipo),
    CONSTRAINT CK_AUTOMOVIL_ANNIO CHECK(annio >= 1900 AND annio <= EXTRACT(YEAR FROM SYSDATE)),
    CONSTRAINT CK_AUTOMOVIL_CANT_PUERTAS CHECK(cant_puertas BETWEEN 2 AND 5),
    CONSTRAINT CK_AUTOMOVIL_KM CHECK(km >= 0)
);

CREATE TABLE MANTENCION (
    num_mantencion NUMBER(4) NOT NULL,
    cod_sucursal CHAR(3) NOT NULL,
    fecha_ingreso DATE,
    fecha_salida DATE,
    patente_auto CHAR(8),
    cod_mecanico NUMBER(5) NOT NULL,
    estado VARCHAR2(15),
    CONSTRAINT PK_MANTENCION PRIMARY KEY(num_mantencion, cod_sucursal),
    CONSTRAINT FK_MANT_AUTOMOVIL FOREIGN KEY(patente_auto) REFERENCES AUTOMOVIL(patente),
    CONSTRAINT FK_MANT_MECANICO FOREIGN KEY(cod_mecanico) REFERENCES MECANICO(cod_mecanico),
    CONSTRAINT FK_MANT_SUCURSAL FOREIGN KEY(cod_sucursal) REFERENCES SUCURSAL(id_sucursal),
    CONSTRAINT CK_MANTENCION_FECHAS CHECK(fecha_salida IS NULL OR fecha_salida >= fecha_ingreso),
    CONSTRAINT CK_MANTENCION_ESTADO CHECK(UPPER(estado) IN ('RESERVA', 'INGRESADO', 'ENTREGADO', 'ANULADO'))
);

CREATE TABLE DETALLE_SERVICIO (
    mantencion_num NUMBER(4) NOT NULL,
    cod_sucursal CHAR(3) NOT NULL,
    cod_servicio NUMBER(3) NOT NULL,
    descuento_serv NUMBER(4,3) NOT NULL,
    cantidad NUMBER(3) NOT NULL,
    CONSTRAINT PK_DETALLE_SERVICIO PRIMARY KEY(mantencion_num, cod_sucursal, cod_servicio),
    CONSTRAINT FK_DET_SER_MANTENCION FOREIGN KEY(mantencion_num, cod_sucursal) REFERENCES MANTENCION(num_mantencion, cod_sucursal),
    CONSTRAINT FK_DET_SER_SERVICIO FOREIGN KEY(cod_servicio) REFERENCES SERVICIO(id_servicio),
    CONSTRAINT CK_DETALLE_SERVICIO_CANTIDAD CHECK(cantidad > 0),
    CONSTRAINT CK_DETALLE_SERVICIO_DESCUENTO CHECK(descuento_serv BETWEEN 0 AND 1)
);


--------------------------------------------------------
-- 3. POBLAMIENTO DE DATOS (DML - Insert)
--------------------------------------------------------

INSERT INTO PAIS(nom_pais) VALUES('Chile');
INSERT INTO PAIS(nom_pais) VALUES('Peru');
INSERT INTO PAIS(nom_pais) VALUES('Colombia');

INSERT INTO CIUDAD(id_ciudad, nom_ciudad, cod_pais) VALUES(165, 'Santiago', 9);
INSERT INTO CIUDAD(id_ciudad, nom_ciudad, cod_pais) VALUES(170, 'Lima', 10);
INSERT INTO CIUDAD(id_ciudad, nom_ciudad, cod_pais) VALUES(175, 'Bogotá', 11);

INSERT INTO SUCURSAL(id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad) VALUES('S01', 'Providencia', 'A. A. Varas', 234, 165);
INSERT INTO SUCURSAL(id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad) VALUES('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);
INSERT INTO SUCURSAL(id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad) VALUES('S03', 'El Cafetero', 'Av. El Faro', 900, 175);

-- Mecánico 460: Jefe de taller (con bono), sin supervisor
INSERT INTO MECANICO(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor) VALUES('Jorge', 'Pablo', 'Soto', 'Sierpe', 5400000, 2759000, 223580, NULL);
-- Mecánico 461: Sin bono de jefatura (NULL), sin supervisor
INSERT INTO MECANICO(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor) VALUES('Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);
-- Mecánico 462: Con bono de jefatura (0), supervisor: 460
INSERT INTO MECANICO(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor) VALUES('Sandra', 'Josefa', 'Letelier', 'S.', 0, 659000, 22358, 460);
-- Mecánico 463: Sin bono de jefatura (NULL), supervisor: 460
INSERT INTO MECANICO(pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor) VALUES('Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);

-- Hacemos commit de los datos guardados
COMMIT;


--------------------------------------------------------
-- 4. INFORME 1 (Consultas SELECT)
--------------------------------------------------------
-- Se requiere simular el sueldo de los mecánicos aplicando un ajuste en los impuestos.
-- Listado de mecánicos cuyo bono de jefatura es nulo y monto de impuestos es inferior a 40.000.

SELECT
    cod_mecanico AS "ID_MECANICO",
    pnombre || ' ' || apaterno AS "NOMBRE_MECANICO",
    sueldo AS "SALARIO",
    monto_impuestos AS "IMPUESTO_ACTUAL",
    monto_impuestos * 0.8 AS "IMPUESTO_REBAJADO",
    sueldo - (monto_impuestos * 0.8) AS "SUELDO_CON_REBAJA_IMPUESTOS"
FROM MECANICO
WHERE bono_jefatura IS NULL 
  AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;
